"use client";

import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "en" | "th";

const T = {
  en: {
    nav: {
      explore:   "Explore",
      swipe:     "♥ Swipe",
      reels:     "▶ Reels",
      buy:       "Buy",
      rent:      "Rent",
      shortStay: "Short Stay",
      signIn:    "Sign In",
      saved:     "Saved",
      signOut:   "Sign Out",
      browse:    "Browse",
      home:      "Home",
      language:  "Language",
      adminDashboard: "Admin Dashboard",
    },
    hero: {
      tag:         "Bangkok · Premium Properties",
      h1a:         "Find your next",
      h1b:         "home in Bangkok.",
      sub:         "Condos, houses and short stays — curated for expats and internationals who want to live well in Bangkok.",
      tabBuy:      "Buy",
      tabRent:     "Long Rent",
      tabShort:    "Short Stay",
      placeholder: "Area, district or property name…",
      search:      "Search",
      listings:    "Listings",
      from:        "From",
      response:    "Response",
      verifiedListings: "Verified Listings",
    },
    browse: {
      label:    "How You Browse",
      title:    "Three ways to find your property",
      swipeName:"Swipe Mode",
      swipeDesc:"Browse properties like you'd browse dating apps. Swipe right to save, left to skip.",
      gridName: "Grid Browse",
      gridDesc: "Classic search with filters. See all listings at once.",
      reelName: "Property Reels",
      reelDesc: "Scroll short video tours. See it before you visit.",
    },
    category: {
      label: "Browse by Category",
      title: "Find your perfect match",
      all:   "All listings",
      lookingIn: "Looking for property in",
      nearBts: "Near BTS & MRT",
      petFriendly: "Pet Friendly",
      propsForYou: "Properties for you",
      props: "Props",
      areas: {
        sukhumvit: "Sukhumvit",
        sathorn: "Sathorn",
        thongLo: "Thong Lo BTS",
        asok: "Asok MRT",
        ekkamai: "Ekkamai",
        silom: "Silom",
        onNut: "On Nut",
        ari: "Ari",
      },
    },
    latest: {
      label:  "Just Listed",
      title:  "Latest Properties",
      seeAll: "See all",
    },
    blog: {
      label:   "Local Guides",
      title:   "Know Bangkok before you arrive",
      all:     "All guides",
      read:    "Read more",
      minRead: "min read",
      blogCategories: {
        neighbourhood: "Neighbourhood Guide",
        expatTips: "Expat Tips",
        propertyInsights: "Property Insights",
        familyLiving: "Family Living",
      },
    },
    trust: {
      v1l: "Verified listings only",    v1s: "Every property manually reviewed",
      v2l: "English-speaking team",     v2s: "No language barrier, ever",
      v3l: "24h response",              v3s: "Via WhatsApp, Line or Telegram",
      v4l: "No hidden fees",            v4s: "Free to browse and enquire",
    },
    talk: {
      label:    "We're here to help",
      title:    "Not sure where to start?",
      sub:      "Tell us your budget, preferred area and move-in date. Our team responds within 24 hours with a curated shortlist — at no charge.",
      whatsapp: "WhatsApp Us",
      line:     "Message on Line",
      telegram: "Telegram",
      emailUs:  "Email Us",
      note:     "Free service · No commitment · English spoken",
    },
    explore: {
      title:    "Explore Bangkok Properties",
      subtitle: "listings · For sale, long rent & short stay",
      noResult: "No properties found",
      noSub:    "Try adjusting your filters or search term",
      clearAll: "Clear all filters",
      showing:  "properties found",
      allProperties: "All Properties",
    },
    property: {
      forSale:   "For Sale",
      longRent:  "Long Rent",
      shortStay: "Short Stay",
      featured:  "Featured",
      interested:"I'm Interested",
      save:      "Save",
      beds:      "Bed",
      studio:    "Studio",
      bath:      "Bath",
    },
    footer: {
      tagline: "Bangkok's premium property platform for expats, digital nomads and international residents looking to buy, rent or stay.",
      browse:  "Browse",
      areas:   "Areas",
      contact: "Contact",
      copy:    "© 2026 New Homes Property · Bangkok",
      forSale: "For Sale",
      longRent: "Long Rent",
      shortStay: "Short Stay",
      swipeMode: "Swipe Mode",
      reels: "Reels",
      silomSathorn: "Silom / Sathorn",
      aboutNhp: "About NHP",
      privacyPolicy: "Privacy Policy",
      sukhumvit: "Sukhumvit",
      thongLo: "Thong Lo",
      asok: "Asok",
      onNut: "On Nut",
    },
    cta: {
      ready: "Ready to move?",
      waitingA: "Bangkok is waiting",
      waitingB: "for you.",
      sub: "120+ verified properties for sale, long-term rent, and short stays. Curated for those who want to live well in Bangkok.",
      browse: "Browse Properties",
      watchReels: "Watch Reels",
    },
    interest: {
      title: "Interested in a property?",
      sub: "Leave your details and we'll contact you within 24 hours via WhatsApp or Line.",
      sent: "✅ Enquiry sent!",
      reachOut: "We'll reach out via {method} within 24 hours.",
      placeholderName: "Your name",
      placeholderNumber: "Your number",
      sending: "Sending…",
      sendButton: "Send Enquiry →",
    },
    filters: {
      searchPlaceholder: "Search area or property…",
      anyBudget: "Any Budget",
      upTo: "Up to",
      clearAll: "Clear all",
      filtersTitle: "Filters",
      lookingFor: "Looking for",
      area: "Area",
      budget: "Budget",
      minimum: "Minimum",
      maximum: "Maximum",
      bedrooms: "Bedrooms",
      propertyType: "Property type",
      amenities: "Amenities",
      sortBy: "Sort by",
      showResults: "Show {total} {label}",
      property: "property",
      properties: "properties",
      petFriendly: "🐾 Pet Friendly",
      nearBts: "🚇 Near BTS / MRT",
      tabAll: "All",
      tabSale: "For Sale",
      tabRent: "Long Rent",
      tabShort: "Short Stay",
      anyType: "Any Type",
      condo: "Condo",
      house: "House",
      villa: "Villa",
      townhouse: "Townhouse",
      apartment: "Apartment",
      anyBeds: "Any Beds",
      anyBed: "Any",
      studio: "Studio",
      bedSingle: "Bed",
      bedsPlural: "Beds",
      sortNewest: "Newest",
      sortPriceAsc: "Price: Low–High",
      sortPriceDesc: "Price: High–Low",
      sortPopular: "Most Popular",
      noMin: "No min",
      noMax: "No max",
      perNight: "/n",
      perMonth: "/mo",
    },
  },

  th: {
    nav: {
      explore:   "สำรวจ",
      swipe:     "♥ สไวป์",
      reels:     "▶ รีลส์",
      buy:       "ซื้อ",
      rent:      "เช่า",
      shortStay: "พักระยะสั้น",
      signIn:    "เข้าสู่ระบบ",
      saved:     "บันทึก",
      signOut:   "ออกจากระบบ",
      browse:    "ดูทั้งหมด",
      home:      "หน้าแรก",
      language:  "ภาษา",
      adminDashboard: "ระบบจัดการ",
    },
    hero: {
      tag:         "กรุงเทพฯ · อสังหาริมทรัพย์พรีเมียม",
      h1a:         "ค้นหาบ้านใหม่",
      h1b:         "ของคุณในกรุงเทพฯ",
      sub:         "คอนโด บ้าน และที่พักระยะสั้น — คัดสรรสำหรับชาวต่างชาติที่ต้องการใช้ชีวิตอย่างดีในกรุงเทพฯ",
      tabBuy:      "ซื้อ",
      tabRent:     "เช่าระยะยาว",
      tabShort:    "พักระยะสั้น",
      placeholder: "ย่าน เขต หรือชื่ออสังหาริมทรัพย์…",
      search:      "ค้นหา",
      listings:    "รายการ",
      from:        "เริ่มต้น",
      response:    "ตอบกลับ",
      verifiedListings: "ยืนยันแล้ว",
    },
    browse: {
      label:    "วิธีการค้นหา",
      title:    "สามวิธีในการหาอสังหาริมทรัพย์",
      swipeName:"โหมดสไวป์",
      swipeDesc:"เรียกดูอสังหาริมทรัพย์เหมือนแอปหาคู่ สไวป์ขวาเพื่อบันทึก สไวป์ซ้ายเพื่อข้าม",
      gridName: "ค้นหาแบบกริด",
      gridDesc: "ค้นหาแบบคลาสสิกพร้อมตัวกรอง ดูรายการทั้งหมดพร้อมกัน",
      reelName: "รีลส์อสังหาริมทรัพย์",
      reelDesc: "เลื่อนดูวิดีโอทัวร์สั้นๆ ดูก่อนไปเยี่ยมชมจริง",
    },
    category: {
      label: "ค้นหาตามหมวดหมู่",
      title: "ค้นหาสิ่งที่ใช่สำหรับคุณ",
      all:   "ดูทั้งหมด",
      lookingIn: "กำลังหาอสังหาริมทรัพย์ใน",
      nearBts: "ใกล้รถไฟฟ้า BTS & MRT",
      petFriendly: "เลี้ยงสัตว์ได้",
      propsForYou: "รายการสำหรับคุณ",
      props: "รายการ",
      areas: {
        sukhumvit: "สุขุมวิท",
        sathorn: "สาทร",
        thongLo: "บีทีเอส ทองหล่อ",
        asok: "เอ็มอาร์ที อโศก",
        ekkamai: "เอกมัย",
        silom: "สีลม",
        onNut: "อ่อนนุช",
        ari: "อารีย์",
      },
    },
    latest: {
      label:  "เพิ่งลงประกาศ",
      title:  "อสังหาริมทรัพย์ล่าสุด",
      seeAll: "ดูทั้งหมด",
    },
    blog: {
      label:   "คู่มือท้องถิ่น",
      title:   "รู้จักกรุงเทพฯ ก่อนเดินทาง",
      all:     "คู่มือทั้งหมด",
      read:    "อ่านเพิ่มเติม",
      minRead: "นาที",
      blogCategories: {
        neighbourhood: "คู่มือย่านที่อยู่อาศัย",
        expatTips: "เคล็ดลับสำหรับชาวต่างชาติ",
        propertyInsights: "ข้อมูลเชิงลึกอสังหาฯ",
        familyLiving: "การใช้ชีวิตครอบครัว",
      },
    },
    trust: {
      v1l: "รายการที่ผ่านการยืนยัน",  v1s: "ทุกอสังหาฯ ผ่านการตรวจสอบด้วยตนเอง",
      v2l: "ทีมพูดภาษาอังกฤษ",         v2s: "ไม่มีอุปสรรคด้านภาษา",
      v3l: "ตอบกลับภายใน 24 ชม.",       v3s: "ผ่าน WhatsApp, Line หรือ Telegram",
      v4l: "ไม่มีค่าใช้จ่ายแอบแฝง",   v4s: "ฟรีในการค้นหาและสอบถาม",
    },
    talk: {
      label:    "เราพร้อมช่วยเหลือ",
      title:    "ไม่แน่ใจจะเริ่มต้นอย่างไร?",
      sub:      "บอกงบประมาณ ย่านที่ต้องการ และวันย้ายเข้า ทีมเราจะตอบกลับภายใน 24 ชั่วโมงพร้อมรายชื่อที่คัดสรรมาให้ — ฟรี",
      whatsapp: "WhatsApp",
      line:     "ข้อความบน Line",
      telegram: "Telegram",
      emailUs:  "ส่งอีเมลหาเรา",
      note:     "บริการฟรี · ไม่มีข้อผูกมัด · มีทีมพูดภาษาอังกฤษ",
    },
    explore: {
      title:    "สำรวจอสังหาริมทรัพย์กรุงเทพฯ",
      subtitle: "รายการ · ขาย เช่าระยะยาว และพักระยะสั้น",
      noResult: "ไม่พบอสังหาริมทรัพย์",
      noSub:    "ลองปรับตัวกรองหรือคำค้นหา",
      clearAll: "ล้างตัวกรองทั้งหมด",
      showing:  "อสังหาริมทรัพย์ที่พบ",
      allProperties: "อสังหาริมทรัพย์ทั้งหมด",
    },
    property: {
      forSale:   "ขาย",
      longRent:  "เช่าระยะยาว",
      shortStay: "พักระยะสั้น",
      featured:  "แนะนำ",
      interested:"สนใจ",
      save:      "บันทึก",
      beds:      "ห้องนอน",
      studio:    "สตูดิโอ",
      bath:      "ห้องน้ำ",
    },
    footer: {
      tagline: "แพลตฟอร์มอสังหาริมทรัพย์พรีเมียมของกรุงเทพฯ สำหรับชาวต่างชาติ นักเดินทาง และผู้พักอาศัย",
      browse:  "ค้นหา",
      areas:   "ย่าน",
      contact: "ติดต่อ",
      copy:    "© 2026 New Homes Property · กรุงเทพฯ",
      forSale: "ขาย",
      longRent: "เช่าระยะยาว",
      shortStay: "พักระยะสั้น",
      swipeMode: "โหมดสไวป์",
      reels: "รีลส์",
      silomSathorn: "สีลม / สาทร",
      aboutNhp: "เกี่ยวกับ NHP",
      privacyPolicy: "นโยบายความเป็นส่วนตัว",
      sukhumvit: "สุขุมวิท",
      thongLo: "ทองหล่อ",
      asok: "อโศก",
      onNut: "อ่อนนุช",
    },
    cta: {
      ready: "พร้อมย้ายเข้าหรือยัง?",
      waitingA: "กรุงเทพฯ กำลังรอต้อนรับ",
      waitingB: "คุณอยู่",
      sub: "อสังหาฯ ที่ผ่านการยืนยันแล้วกว่า 120 รายการ สำหรับขาย เช่าระยะยาว และพักระยะสั้น คัดสรรสำหรับผู้ที่ต้องการใช้ชีวิตอย่างมีระดับในกรุงเทพฯ",
      browse: "ดูอสังหาริมทรัพย์",
      watchReels: "ดูวิดีโอรีลส์",
    },
    interest: {
      title: "สนใจอสังหาริมทรัพย์นี้?",
      sub: "ฝากรายละเอียดของคุณ แล้วเราจะติดต่อกลับภายใน 24 ชั่วโมง ผ่าน WhatsApp หรือ Line",
      sent: "✅ ส่งข้อมูลสอบถามแล้ว!",
      reachOut: "เราจะติดต่อกลับผ่าน {method} ภายใน 24 ชั่วโมง",
      placeholderName: "ชื่อของคุณ",
      placeholderNumber: "เบอร์โทรศัพท์ของคุณ",
      sending: "กำลังส่ง…",
      sendButton: "ส่งข้อมูลสอบถาม →",
    },
    filters: {
      searchPlaceholder: "ค้นหาย่านหรืออสังหาริมทรัพย์…",
      anyBudget: "ทุกงบประมาณ",
      upTo: "ไม่เกิน",
      clearAll: "ล้างทั้งหมด",
      filtersTitle: "ตัวกรอง",
      lookingFor: "ค้นหาสำหรับ",
      area: "ย่าน",
      budget: "งบประมาณ",
      minimum: "ขั้นต่ำ",
      maximum: "สูงสุด",
      bedrooms: "ห้องนอน",
      propertyType: "ประเภทอสังหาริมทรัพย์",
      amenities: "สิ่งอำนวยความสะดวก",
      sortBy: "จัดเรียงตาม",
      showResults: "แสดง {label} ทั้งหมด {total} รายการ",
      property: "รายการ",
      properties: "รายการ",
      petFriendly: "🐾 เลี้ยงสัตว์ได้",
      nearBts: "🚇 ใกล้ BTS / MRT",
      tabAll: "ทั้งหมด",
      tabSale: "ขาย",
      tabRent: "เช่าระยะยาว",
      tabShort: "พักระยะสั้น",
      anyType: "ทุกประเภท",
      condo: "คอนโด",
      house: "บ้าน",
      villa: "วิลล่า/บ้านพักตากอากาศ",
      townhouse: "ทาวน์เฮ้าส์",
      apartment: "อพาร์ทเม้นท์",
      anyBeds: "ทุกห้องนอน",
      anyBed: "ทั้งหมด",
      studio: "สตูดิโอ",
      bedSingle: "ห้องนอน",
      bedsPlural: "ห้องนอน",
      sortNewest: "ล่าสุด",
      sortPriceAsc: "ราคา: ต่ำ–สูง",
      sortPriceDesc: "ราคา: สูง–ต่ำ",
      sortPopular: "ได้รับความนิยมสูงสุด",
      noMin: "ไม่มีขั้นต่ำ",
      noMax: "ไม่มีสูงสุด",
      perNight: "/คืน",
      perMonth: "/เดือน",
    },
  },
} as const;

type Translations = typeof T.en;

interface LangCtx {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
}

const LanguageContext = createContext<LangCtx>({
  lang: "en",
  setLang: () => {},
  t: T.en,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: T[lang] as Translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
