"use client";

import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "en" | "th" | "zh";

const T = {
  en: {
    nav: {
      explore:   "Explore",
      swipe:     "Swipe",
      reels:     "Reels",
      buy:       "Buy",
      rent:      "Rent",
      shortStay: "Short Stay",
      signIn:    "Sign In",
      saved:     "Saved",
      signOut:   "Sign Out",
      browse:    "Browse",
      home:      "Home",
      language:  "Language",
      adminDashboard: "Admin Dashboard",
      discover: "Discover Properties",
      imLookingFor: "I’m Interested In",
      petFriendly: "Pet Friendly",
      renting: "Renting",
      buying: "Buying",
    },
    hero: {
      tag:         "Bangkok · Neighbourhood Properties",
      h1a:         "Where Would You",
      h1b:         "Belong in Bangkok?",
      sub:         "Discover neighborhoods that match your lifestyle, goals, and budget — before you find your home.",
      tabBuy:      "Buy",
      tabRent:     "Rent",
      tabShort:    "Smart Search",
      placeholder: "Area, district or property name…",
      search:      "Search",
      listings:    "Listings",
      from:        "From",
      response:    "Response",
      verifiedListings: "Verified Listings",
    },
    browse: {
      label:    "How You Browse",
      title:    "Three ways to find your property",
      swipeName:"Auto Finder",
      swipeDesc:"Find your perfect Bangkok neighborhood and condos designed for how you want to live.",
      gridName: "Grid Browse",
      gridDesc: "Classic search with filters. See all listings at once.",
      reelName: "Swipe Mode",
      reelDesc: "Browse properties Tinder-style. Swipe right to like, left to pass.",
    },
    category: {
      label: "Browse by Category",
      title: "Find your perfect match",
      all:   "View All",
      lookingIn: "Looking for property in",
      nearBts: "Near BTS & MRT",
      petFriendly: "Pet Friendly",
      newHubs: "Other Bangkok Areas",
      propsForYou: "Properties for you",
      props: "Props",
      areas: {
        sukhumvit: "Sukhumvit",
        sathorn: "Sathorn",
        thongLo: "Thong Lo",
        asok: "Asok MRT",
        ekkamai: "Ekkamai",
        silom: "Silom",
        onNut: "On Nut",
        ari: "Ari",
        rama9: "Rama 9",
        bangNa: "Bang Na",
        huaiKhwang: "Huai Khwang",
        phayaThai: "Phaya Thai",
        chatuchak: "Chatuchak",
        rama4: "Rama 4",
        charoenkrung: "Charoenkrung",
        samYan: "Sam Yan",
        khlongSan: "Khlong San",
        phraKhanong: "Phra Khanong",
      },
    },
    latest: {
      label:  "Just Listed",
      title:  "Latest Properties",
      seeAll: "See all",
    },
    blog: {
      label:   "Local Guides",
      title:   "Know Bangkok before you arrive",
      all:     "All guides",
      read:    "Read more",
      minRead: "min read",
      blogCategories: {
        neighbourhood: "Neighbourhood Guide",
        expatTips: "Expat Tips",
        propertyInsights: "Property Insights",
        familyLiving: "Family Living",
      },
    },
    trust: {
      v1l: "Verified listings only",    v1s: "Every property manually reviewed",
      v2l: "English-speaking team",     v2s: "No language barrier, ever",
      v3l: "24h response",              v3s: "Via WhatsApp, Line or Telegram",
      v4l: "No hidden fees",            v4s: "Free to browse and enquire",
    },
    talk: {
      label:    "We're here to help",
      title:    "Not sure where to start?",
      sub:      "Tell us your budget, preferred area and move-in date. Our team responds within 24 hours with a curated shortlist — at no charge.",
      whatsapp: "WhatsApp Us",
      line:     "Message on Line",
      telegram: "Telegram",
      emailUs:  "Email Us",
      note:     "Free service · No commitment · English spoken",
    },
    explore: {
      title:    "Explore Bangkok Properties",
      subtitle: "listings · For sale, long rent & short stay",
      noResult: "No properties found",
      noSub:    "Try adjusting your filters or search term",
      clearAll: "Clear all filters",
      showing:  "properties found",
      allProperties: "All Properties",
    },
    property: {
      forSale:   "For Sale",
      longRent:  "Long Rent",
      shortStay: "Short Stay",
      featured:  "Featured",
      interested:"I'm Interested",
      save:      "Save",
      beds:      "Bed",
      studio:    "Studio",
      bath:      "Bath",
    },
    footer: {
      tagline: "Bangkok's neighbourhood property platform for expats, digital nomads and international residents looking to buy, rent or stay.",
      browse:  "Browse",
      areas:   "Areas",
      contact: "Contact",
      copy:    "© 2026 New Home Property · Bangkok",
      forSale: "For Sale",
      longRent: "Long Rent",
      shortStay: "Short Stay",
      swipeMode: "Swipe Mode",
      reels: "Reels",
      silomSathorn: "Silom / Sathorn",
      aboutNhp: "About NHP",
      privacyPolicy: "Privacy Policy",
      sukhumvit: "Sukhumvit",
      thongLo: "Thong Lo",
      asok: "Asok",
      onNut: "On Nut",
    },
    cta: {
      ready: "Ready to move?",
      waitingA: "Bangkok is waiting",
      waitingB: "for you.",
      sub: "120+ verified properties for sale, long-term rent, and short stays. Curated for those who want to live well in Bangkok.",
      browse: "Browse Properties",
      watchReels: "Watch Reels",
    },
    interest: {
      title: "Interested in a property?",
      sub: "Leave your details and we'll contact you within 24 hours via WhatsApp or Line.",
      sent: "Enquiry sent!",
      reachOut: "We'll reach out via {method} within 24 hours.",
      placeholderName: "Your name",
      placeholderNumber: "Your number",
      sending: "Sending…",
      sendButton: "Send Enquiry →",
    },
    filters: {
      searchPlaceholder: "Search area or property…",
      anyBudget: "Any Budget",
      upTo: "Up to",
      clearAll: "Clear all",
      filtersTitle: "Filters",
      lookingFor: "Looking for",
      area: "Area",
      budget: "Budget",
      minimum: "Minimum",
      maximum: "Maximum",
      bedrooms: "Bedrooms",
      propertyType: "Property type",
      amenities: "Amenities",
      sortBy: "Sort by",
      showResults: "Show {total} {label}",
      property: "property",
      properties: "properties",
      petFriendly: "Pet Friendly",
      nearBts: "Near BTS / MRT",
      tabAll: "All",
      tabSale: "For Sale",
      tabRent: "Long Rent",
      tabShort: "Short Stay",
      anyType: "Any Type",
      condo: "Condo",
      house: "House",
      villa: "Villa",
      townhouse: "Townhouse",
      apartment: "Apartment",
      anyBeds: "Any Beds",
      anyBed: "Any",
      studio: "Studio",
      bedSingle: "Bed",
      bedsPlural: "Beds",
      sortNewest: "Newest",
      sortPriceAsc: "Price: Low–High",
      sortPriceDesc: "Price: High–Low",
      sortPopular: "Most Popular",
      noMin: "No min",
      noMax: "No max",
      perNight: "/n",
      perMonth: "/mo",
    },
    discoveryGrid: {
      label: "DISCOVER BANGKOK. FIND YOUR PERFECT PLACE.",
      title: "Three ways to find your ideal home",
      subtitle: "Personalized matching, interactive exploration, and handpicked homes",
      card1: {
        tag: "01 MATCH YOUR LIFESTYLE",
        title: "Find the Bangkok neighborhood that fits you best.",
        desc: "Answer a few simple questions and get personalized neighborhood recommendations that match your lifestyle, budget, and goals.",
        button: "Start Matching",
        matchedText: "10,000+ people already matched",
      },
      card2: {
        tag: "02 EXPLORE THE MAP",
        title: "Explore Bangkok visually.",
        desc: "Discover neighborhoods, transport connections, amenities, and what makes each area unique.",
        button: "Explore the Map",
        tags: {
          access: "Access",
          intlSchools: "International Schools",
          shopping: "Shopping & Dining",
          greenSpaces: "Green Spaces",
        },
        pins: {
          ari: { name: "Ari", label: "Trendy · Vibrant" },
          thonglor: { name: "Thonglor", label: "Luxury · Lifestyle" },
          ekkamai: { name: "Ekkamai", label: "Trendy · Convenient" },
          sathorn: { name: "Sathorn", label: "Business · Central" },
        }
      },
      card3: {
        tag: "03 DISCOVER HOMES",
        title: "Handpicked homes in neighborhoods you'll love.",
        desc: "Beautiful places, quality living, carefully selected for you.",
        button: "Browse Homes",
      },
      tabs: {
        card1: "Match",
        card2: "Map",
        card3: "Homes",
      }
    },
  },

  th: {
    nav: {
      explore:   "สำรวจ",
      swipe:     "สไวป์",
      reels:     "รีลส์",
      buy:       "ซื้อ",
      rent:      "เช่า",
      shortStay: "พักระยะสั้น",
      signIn:    "เข้าสู่ระบบ",
      saved:     "บันทึก",
      signOut:   "ออกจากระบบ",
      browse:    "ดูทั้งหมด",
      home:      "หน้าแรก",
      language:  "ภาษา",
      adminDashboard: "ระบบจัดการ",
      discover: "ค้นพบอสังหาริมทรัพย์",
      imLookingFor: "ฉันสนใจใน",
      petFriendly: "เลี้ยงสัตว์ได้",
      renting: "เช่า",
      buying: "ซื้อ",
    },
    hero: {
      tag:         "กรุงเทพฯ · อสังหาริมทรัพย์ในย่านต่างๆ",
      h1a:         "คุณควรอยู่ย่านไหน",
      h1b:         "ในกรุงเทพฯ?",
      sub:         "ค้นหาย่านที่ตรงกับไลฟ์สไตล์ เป้าหมาย และงบประมาณของคุณ — ก่อนที่คุณจะเลือกบ้าน",
      tabBuy:      "ซื้อ",
      tabRent:     "เช่า",
      tabShort:    "ค้นหาอัจฉริยะ",
      placeholder: "ย่าน เขต หรือชื่ออสังหาริมทรัพย์…",
      search:      "ค้นหา",
      listings:    "รายการ",
      from:        "เริ่มต้น",
      response:    "ตอบกลับ",
      verifiedListings: "ยืนยันแล้ว",
    },
    browse: {
      label:    "วิธีการค้นหา",
      title:    "สามวิธีในการหาอสังหาริมทรัพย์",
      swipeName:"ออโต้ไฟนเดอร์ (Auto Finder)",
      swipeDesc:"ค้นหาย่านและคอนโดที่ใช่ในกรุงเทพฯ ที่ออกแบบมาเพื่อการใช้ชีวิตในแบบที่คุณต้องการ",
      gridName: "ค้นหาแบบกริด",
      gridDesc: "ค้นหาแบบคลาสสิกพร้อมตัวกรอง ดูรายการทั้งหมดพร้อมกัน",
      reelName: "โหมดสไวป์",
      reelDesc: "เลือกดูอสังหาริมทรัพย์สไตล์ทินเดอร์ ปัดขวาเพื่อถูกใจ ปัดซ้ายเพื่อข้าม",
    },
    category: {
      label: "ค้นหาตามหมวดหมู่",
      title: "ค้นหาสิ่งที่ใช่สำหรับคุณ",
      all:   "ดูทั้งหมด",
      lookingIn: "กำลังหาอสังหาริมทรัพย์ใน",
      nearBts: "ใกล้รถไฟฟ้า BTS & MRT",
      petFriendly: "เลี้ยงสัตว์ได้",
      newHubs: "พื้นที่อื่นในกรุงเทพฯ",
      propsForYou: "รายการสำหรับคุณ",
      props: "รายการ",
      areas: {
        sukhumvit: "สุขุมวิท",
        sathorn: "สาทร",
        thongLo: "ทองหล่อ",
        asok: "เอ็มอาร์ที อโศก",
        ekkamai: "เอกมัย",
        silom: "สีลม",
        onNut: "อ่อนนุช",
        ari: "อารีย์",
        rama9: "พระราม 9",
        bangNa: "บางนา",
        huaiKhwang: "ห้วยขวาง",
        phayaThai: "พญาไท",
        chatuchak: "จตุจักร",
        rama4: "พระราม 4",
        charoenkrung: "เจริญกรุง",
        samYan: "สามย่าน",
        khlongSan: "คลองสาน",
        phraKhanong: "พระโขนง",
      },
    },
    latest: {
      label:  "เพิ่งลงประกาศ",
      title:  "อสังหาริมทรัพย์ล่าสุด",
      seeAll: "ดูทั้งหมด",
    },
    blog: {
      label:   "คู่มือท้องถิ่น",
      title:   "รู้จักกรุงเทพฯ ก่อนเดินทาง",
      all:     "คู่มือทั้งหมด",
      read:    "อ่านเพิ่มเติม",
      minRead: "นาที",
      blogCategories: {
        neighbourhood: "คู่มือย่านที่อยู่อาศัย",
        expatTips: "เคล็ดลับสำหรับชาวต่างชาติ",
        propertyInsights: "ข้อมูลเชิงลึกอสังหาฯ",
        familyLiving: "การใช้ชีวิตครอบครัว",
      },
    },
    trust: {
      v1l: "รายการที่ผ่านการยืนยัน",  v1s: "ทุกอสังหาฯ ผ่านการตรวจสอบด้วยตนเอง",
      v2l: "ทีมพูดภาษาอังกฤษ",         v2s: "ไม่มีอุปสรรคด้านภาษา",
      v3l: "ตอบกลับภายใน 24 ชม.",       v3s: "ผ่าน WhatsApp, Line หรือ Telegram",
      v4l: "ไม่มีค่าใช้จ่ายแอบแฝง",   v4s: "ฟรีในการค้นหาและสอบถาม",
    },
    talk: {
      label:    "เราพร้อมช่วยเหลือ",
      title:    "ไม่แน่ใจจะเริ่มต้นอย่างไร?",
      sub:      "บอกงบประมาณ ย่านที่ต้องการ และวันย้ายเข้า ทีมเราจะตอบกลับภายใน 24 ชั่วโมงพร้อมรายชื่อที่คัดสรรมาให้ — ฟรี",
      whatsapp: "WhatsApp",
      line:     "ข้อความบน Line",
      telegram: "Telegram",
      emailUs:  "ส่งอีเมลหาเรา",
      note:     "บริการฟรี · ไม่มีข้อผูกมัด · มีทีมพูดภาษาอังกฤษ",
    },
    explore: {
      title:    "สำรวจอสังหาริมทรัพย์กรุงเทพฯ",
      subtitle: "รายการ · ขาย เช่าระยะยาว และพักระยะสั้น",
      noResult: "ไม่พบอสังหาริมทรัพย์",
      noSub:    "ลองปรับตัวกรองหรือคำค้นหา",
      clearAll: "ล้างตัวกรองทั้งหมด",
      showing:  "อสังหาริมทรัพย์ที่พบ",
      allProperties: "อสังหาริมทรัพย์ทั้งหมด",
    },
    property: {
      forSale:   "ขาย",
      longRent:  "เช่าระยะยาว",
      shortStay: "พักระยะสั้น",
      featured:  "แนะนำ",
      interested:"สนใจ",
      save:      "บันทึก",
      beds:      "ห้องนอน",
      studio:    "สตูดิโอ",
      bath:      "ห้องน้ำ",
    },
    footer: {
      tagline: "แพลตฟอร์มอสังหาริมทรัพย์ในย่านต่างๆ ของกรุงเทพฯ สำหรับชาวต่างชาติ นักเดินทาง และผู้พักอาศัย",
      browse:  "ค้นหา",
      areas:   "ย่าน",
      contact: "ติดต่อ",
      copy:    "© 2026 New Home Property · กรุงเทพฯ",
      forSale: "ขาย",
      longRent: "เช่าระยะยาว",
      shortStay: "พักระยะสั้น",
      swipeMode: "โหมดสไวป์",
      reels: "รีลส์",
      silomSathorn: "สีลม / สาทร",
      aboutNhp: "เกี่ยวกับ NHP",
      privacyPolicy: "นโยบายความเป็นส่วนตัว",
      sukhumvit: "สุขุมวิท",
      thongLo: "ทองหล่อ",
      asok: "อโศก",
      onNut: "อ่อนนุช",
    },
    cta: {
      ready: "พร้อมย้ายเข้าหรือยัง?",
      waitingA: "กรุงเทพฯ กำลังรอต้อนรับ",
      waitingB: "คุณอยู่",
      sub: "อสังหาฯ ที่ผ่านการยืนยันแล้วกว่า 120 รายการ สำหรับขาย เช่าระยะยาว และพักระยะสั้น คัดสรรสำหรับผู้ที่ต้องการใช้ชีวิตอย่างมีระดับในกรุงเทพฯ",
      browse: "ดูอสังหาริมทรัพย์",
      watchReels: "ดูวิดีโอรีลส์",
    },
    interest: {
      title: "สนใจอสังหาริมทรัพย์นี้?",
      sub: "ฝากรายละเอียดของคุณ แล้วเราจะติดต่อกลับภายใน 24 ชั่วโมง ผ่าน WhatsApp หรือ Line",
      sent: "ส่งข้อมูลสอบถามแล้ว!",
      reachOut: "เราจะติดต่อกลับผ่าน {method} ภายใน 24 ชั่วโมง",
      placeholderName: "ชื่อของคุณ",
      placeholderNumber: "เบอร์โทรศัพท์ของคุณ",
      sending: "กำลังส่ง…",
      sendButton: "ส่งข้อมูลสอบถาม →",
    },
    filters: {
      searchPlaceholder: "ค้นหาย่านหรืออสังหาริมทรัพย์…",
      anyBudget: "ทุกงบประมาณ",
      upTo: "ไม่เกิน",
      clearAll: "ล้างทั้งหมด",
      filtersTitle: "ตัวกรอง",
      lookingFor: "ค้นหาสำหรับ",
      area: "ย่าน",
      budget: "งบประมาณ",
      minimum: "ขั้นต่ำ",
      maximum: "สูงสุด",
      bedrooms: "ห้องนอน",
      propertyType: "ประเภทอสังหาริมทรัพย์",
      amenities: "สิ่งอำนวยความสะดวก",
      sortBy: "จัดเรียงตาม",
      showResults: "แสดง {label} ทั้งหมด {total} รายการ",
      property: "รายการ",
      properties: "รายการ",
      petFriendly: "เลี้ยงสัตว์ได้",
      nearBts: "ใกล้ BTS / MRT",
      tabAll: "ทั้งหมด",
      tabSale: "ขาย",
      tabRent: "เช่าระยะยาว",
      tabShort: "พักระยะสั้น",
      anyType: "ทุกประเภท",
      condo: "คอนโด",
      house: "บ้าน",
      villa: "วิลล่า/บ้านพักตากอากาศ",
      townhouse: "ทาวน์เฮ้าส์",
      apartment: "อพาร์ทเม้นท์",
      anyBeds: "ทุกห้องนอน",
      anyBed: "ทั้งหมด",
      studio: "สตูดิโอ",
      bedSingle: "ห้องนอน",
      bedsPlural: "ห้องนอน",
      sortNewest: "ล่าสุด",
      sortPriceAsc: "ราคา: ต่ำ–สูง",
      sortPriceDesc: "ราคา: สูง–ต่ำ",
      sortPopular: "ได้รับความนิยมสูงสุด",
      noMin: "ไม่มีขั้นต่ำ",
      noMax: "ไม่มีสูงสุด",
      perNight: "/คืน",
      perMonth: "/เดือน",
    },
    discoveryGrid: {
      label: "ค้นพบกรุงเทพฯ ค้นหาย่านที่สมบูรณ์แบบของคุณ",
      title: "3 วิธีในการค้นหาบ้านในฝันของคุณ",
      subtitle: "การวิเคราะห์จับคู่ย่าน สำรวจแผนที่แบบอินเตอร์แอคทีฟ และบ้านที่คัดสรรมาอย่างดี",
      card1: {
        tag: "01 จับคู่ไลฟ์สไตล์ของคุณ",
        title: "ค้นหาย่านในกรุงเทพฯ ที่เหมาะกับคุณที่สุด",
        desc: "ตอบคำถามง่ายๆ เพียงไม่กี่ข้อเพื่อรับคำแนะนำย่านที่ตรงกับไลฟ์สไตล์ งบประมาณ และเป้าหมายของคุณ",
        button: "เริ่มจับคู่ย่านที่ใช่",
        matchedText: "แมตช์สำเร็จแล้วกว่า 10,000+ คน",
      },
      card2: {
        tag: "02 สำรวจแผนที่",
        title: "สำรวจกรุงเทพฯ ผ่านแผนที่อัจฉริยะ",
        desc: "ค้นพบย่านต่างๆ เส้นทางการเดินทาง สิ่งอำนวยความสะดวก และเอกลักษณ์เฉพาะของแต่ละพื้นที่",
        button: "สำรวจแผนที่",
        tags: {
          access: "การเดินทางสะดวก",
          intlSchools: "โรงเรียนนานาชาติ",
          shopping: "แหล่งช้อปปิ้ง & ร้านอาหาร",
          greenSpaces: "พื้นที่สีเขียว",
        },
        pins: {
          ari: { name: "อารีย์", label: "ชิค · มีชีวิตชีวา" },
          thonglor: { name: "ทองหล่อ", label: "หรูหรา · พรีเมียม" },
          ekkamai: { name: "เอกมัย", label: "ทันสมัย · สะดวกสบาย" },
          sathorn: { name: "สาทร", label: "ย่านธุรกิจ · ใจกลางเมือง" },
        }
      },
      card3: {
        tag: "03 ค้นพบดีไซน์บ้าน",
        title: "บ้านที่คัดสรรมาอย่างดีในย่านที่คุณจะรัก",
        desc: "สถานที่ที่สวยงาม การใช้ชีวิตที่มีคุณภาพ คัดสรรมาเพื่อคุณโดยเฉพาะ",
        button: "เลือกดูบ้าน",
      },
      tabs: {
        card1: "จับคู่ย่าน",
        card2: "แผนที่",
        card3: "บ้านแนะนำ",
      }
    },
  },

  zh: {
    nav: {
      explore:   "探索",
      swipe:     "滑动",
      reels:     "短片",
      buy:       "购买",
      rent:      "租赁",
      shortStay: "短期入住",
      signIn:    "登录",
      saved:     "收藏",
      signOut:   "退出",
      browse:    "浏览全部",
      home:      "首页",
      language:  "语言",
      adminDashboard: "管理后台",
      discover: "发现房源",
      imLookingFor: "我想要",
      petFriendly: "允许宠物",
      renting: "租房",
      buying: "购房",
    },
    hero: {
      tag:         "曼谷 · 社区房产",
      h1a:         "您想住在曼谷",
      h1b:         "哪个社区？",
      sub:         "发现与您的生活方式、目标和预算相匹配的社区 — 在找到家之前。",
      tabBuy:      "购房",
      tabRent:     "租赁",
      tabShort:    "智能搜索",
      placeholder: "区域、地区或房产名称…",
      search:      "搜索",
      listings:    "房源",
      from:        "起价",
      response:    "响应",
      verifiedListings: "已认证房源",
    },
    browse: {
      label:    "浏览方式",
      title:    "三种找房方式",
      swipeName:"智能匹配",
      swipeDesc:"找到符合您生活方式的曼谷完美社区和公寓。",
      gridName: "网格浏览",
      gridDesc: "带筛选器的经典搜索，一次查看所有房源。",
      reelName: "滑动模式",
      reelDesc: "像 Tinder 一样浏览房产，右滑喜欢，左滑跳过。",
    },
    category: {
      label: "按类别浏览",
      title: "找到最适合您的房源",
      all:   "全部房源",
      lookingIn: "正在寻找房产于",
      nearBts: "近BTS & MRT",
      petFriendly: "允许宠物",
      newHubs: "曼谷其他地区",
      propsForYou: "为您推荐的房源",
      props: "房源",
      areas: {
        sukhumvit: "素坤逸",
        sathorn: "沙吞",
        thongLo: "通罗",
        asok: "阿索克MRT",
        ekkamai: "伊卡迈",
        silom: "是隆",
        onNut: "安努",
        ari: "阿里",
        rama9: "拉玛九世",
        bangNa: "邦纳",
        huaiKhwang: "怀匡",
        phayaThai: "帕亚泰",
        chatuchak: "乍都乍",
        rama4: "拉玛四世",
        charoenkrung: "石龙军路",
        samYan: "三养",
        khlongSan: "空讪",
        phraKhanong: "帕卡侬",
      },
    },
    latest: {
      label:  "最新上架",
      title:  "最新房源",
      seeAll: "查看全部",
    },
    blog: {
      label:   "本地指南",
      title:   "到达前了解曼谷",
      all:     "全部指南",
      read:    "阅读更多",
      minRead: "分钟阅读",
      blogCategories: {
        neighbourhood: "社区指南",
        expatTips: "外籍人士贴士",
        propertyInsights: "房产洞察",
        familyLiving: "家庭生活",
      },
    },
    trust: {
      v1l: "仅限认证房源",    v1s: "每套房产均经人工审核",
      v2l: "英语服务团队",    v2s: "无语言障碍",
      v3l: "24小时响应",       v3s: "通过WhatsApp、Line或Telegram",
      v4l: "无隐藏费用",      v4s: "免费浏览和咨询",
    },
    talk: {
      label:    "我们随时为您服务",
      title:    "不知道从哪里开始？",
      sub:      "告诉我们您的预算、首选区域和入住日期。我们的团队将在24小时内为您免费提供精心挑选的短名单。",
      whatsapp: "WhatsApp 联系我们",
      line:     "Line 留言",
      telegram: "Telegram",
      emailUs:  "发送邮件",
      note:     "免费服务 · 无需承诺 · 提供英语服务",
    },
    explore: {
      title:    "探索曼谷房产",
      subtitle: "房源 · 出售、长期租赁及短期入住",
      noResult: "未找到房产",
      noSub:    "尝试调整筛选条件或搜索关键词",
      clearAll: "清除所有筛选",
      showing:  "找到的房源",
      allProperties: "所有房产",
    },
    property: {
      forSale:   "出售",
      longRent:  "长期租赁",
      shortStay: "短期入住",
      featured:  "推荐",
      interested:"我有兴趣",
      save:      "收藏",
      beds:      "卧室",
      studio:    "开间",
      bath:      "浴室",
    },
    footer: {
      tagline: "曼谷面向外籍人士、数字游民和国际居民的社区房产平台，提供购房、租赁及短期入住服务。",
      browse:  "浏览",
      areas:   "区域",
      contact: "联系我们",
      copy:    "© 2026 New Home Property · 曼谷",
      forSale: "出售",
      longRent: "长期租赁",
      shortStay: "短期入住",
      swipeMode: "滑动模式",
      reels: "短片",
      silomSathorn: "是隆 / 沙吞",
      aboutNhp: "关于 NHP",
      privacyPolicy: "隐私政策",
      sukhumvit: "素坤逸",
      thongLo: "通罗",
      asok: "阿索克",
      onNut: "安努",
    },
    cta: {
      ready: "准备好搬家了吗？",
      waitingA: "曼谷正在等待",
      waitingB: "您的到来。",
      sub: "120余套经认证的房产，涵盖出售、长期租赁及短期入住，为追求曼谷高品质生活的人士精心挑选。",
      browse: "浏览房产",
      watchReels: "观看短片",
    },
    interest: {
      title: "对此房产感兴趣？",
      sub: "留下您的联系方式，我们将在24小时内通过WhatsApp或Line与您联系。",
      sent: "咨询已发送！",
      reachOut: "我们将在24小时内通过{method}与您联系。",
      placeholderName: "您的姓名",
      placeholderNumber: "您的电话号码",
      sending: "发送中…",
      sendButton: "发送咨询 →",
    },
    filters: {
      searchPlaceholder: "搜索区域或房产…",
      anyBudget: "不限预算",
      upTo: "最高",
      clearAll: "清除全部",
      filtersTitle: "筛选条件",
      lookingFor: "寻找类型",
      area: "区域",
      budget: "预算",
      minimum: "最低",
      maximum: "最高",
      bedrooms: "卧室",
      propertyType: "房产类型",
      amenities: "配套设施",
      sortBy: "排序方式",
      showResults: "显示 {total} 个{label}",
      property: "房产",
      properties: "房产",
      petFriendly: "允许宠物",
      nearBts: "近BTS / MRT",
      tabAll: "全部",
      tabSale: "出售",
      tabRent: "长期租赁",
      tabShort: "短期入住",
      anyType: "不限类型",
      condo: "公寓",
      house: "独栋住宅",
      villa: "别墅",
      townhouse: "联排别墅",
      apartment: "公寓楼",
      anyBeds: "不限卧室",
      anyBed: "全部",
      studio: "开间",
      bedSingle: "卧室",
      bedsPlural: "卧室",
      sortNewest: "最新",
      sortPriceAsc: "价格：低到高",
      sortPriceDesc: "价格：高到低",
      sortPopular: "最受欢迎",
      noMin: "无最低",
      noMax: "无最高",
      perNight: "/晚",
      perMonth: "/月",
    },
    discoveryGrid: {
      label: "探索曼谷，找到您的理想之所。",
      title: "三种方式找到您的理想家园",
      subtitle: "个性化匹配、互动地图探索和精选房源",
      card1: {
        tag: "01 匹配您的生活方式",
        title: "找到最适合您的曼谷社区。",
        desc: "回答几个简单问题，获取与您的生活方式、预算和目标相匹配的个性化社区推荐。",
        button: "开始匹配",
        matchedText: "已有10,000+人成功匹配",
      },
      card2: {
        tag: "02 探索地图",
        title: "直观探索曼谷。",
        desc: "发现各社区、交通连接、周边设施及每个区域的独特之处。",
        button: "探索地图",
        tags: {
          access: "交通便利",
          intlSchools: "国际学校",
          shopping: "购物 & 餐饮",
          greenSpaces: "绿地",
        },
        pins: {
          ari: { name: "阿里", label: "时尚 · 活力" },
          thonglor: { name: "通罗", label: "豪华 · 生活方式" },
          ekkamai: { name: "伊卡迈", label: "时尚 · 便利" },
          sathorn: { name: "沙吞", label: "商务 · 中心" },
        }
      },
      card3: {
        tag: "03 发现房源",
        title: "在您喜爱的社区精选房源。",
        desc: "精美的居所，高品质生活，专为您精心挑选。",
        button: "浏览房源",
      },
      tabs: {
        card1: "匹配",
        card2: "地图",
        card3: "房源",
      }
    },
  },
} as const;

type Translations = typeof T.en;

interface LangCtx {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: Translations;
}

const LanguageContext = createContext<LangCtx>({
  lang: "en",
  setLang: () => {},
  t: T.en,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");
  return (
    <LanguageContext.Provider value={{ lang, setLang, t: T[lang] as Translations }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
